### ISSUE TITLE
low fps when in-game with amalgam

### ISSUE THREAD

**Issue by 1fbw2** [rei-2/Amalgam#12]
whenever i go in-game without it injected im getting around 60-100 fps, depending on map and players. but whenever I inject it, no matter what config i use, its always at 5-30 fps. even with everything disabled its still like that. how so?

**Comment by godofateris** [comment]
upgrade pc idk

**Comment by acapro200** [comment]
shit pc get new one

**Comment by 1fbw2** [comment]
yo nvm i got vac banned. fuck tf2 and its cheats

**Comment by inrepathy** [comment]
> yo nvm i got vac banned. fuck tf2 and its cheats

bro forgot to use vac bypass

**Comment by hvhlord** [comment]
bro forgot the vac bypass 😭😭💀💀

**Comment by 1fbw2** [comment]
i HAD a vac bypass
idk what u guys are talking about

**Comment by AssociatedWithN** [comment]
how 1 tapped by vac
