### ISSUE TITLE
Heavy spins the machine gun himself

### ISSUE THREAD

**Issue by NEKITDOSHIKk** [rei-2/Amalgam#9]
Heavy spins the machine gun himself
123 config
i dont know

**Comment by NEKITDOSHIKk** [comment]
(i used google translator, i cant speak english well)

**Comment by rei-2** [comment]
> enable debug settings, go to aimbot and you should see something down there like "hold fire" it's under a dropdown or something, search for it 📟

that is only related to holding the attack button, though i did decide to add an autorev toggle under hitscan modifiers

**Comment by NEKITDOSHIKk** [comment]
i disabled aim holds fire, it didnt help

**Comment by NEKITDOSHIKk** [comment]
> enable debug settings, go to aimbot and you should see something down there like "hold fire" it's under a dropdown or something, search for it 📟

i disabled it, didnt help
